### ISSUE TITLE
fmbt-log seperater not working 

### ISSUE THREAD

**Issue by dassio** [01org/fMBT#55]
logfile content :
```
<fmbt_log>
<version>
    0.37-1
</version>
<conf_load>
    <conf_file name="test.conf"/>
     <remote_pyaal_version>0.37-1</remote_pyaal_version>
</conf_load>
<conf_execute>
    <action_name name="i%3Acallee%3D%27Alice%27"/>
    <action_name name="i%3Acallee%3D%27Bob%27"/>
    <action_name name="i%3AphoneApp%3D%27Skype%27"/>
    <action_name name="i%3AphoneApp%3D%27WhatsApp%27"/>
    <action_name name="i%3Acall"/>
    <action_name name="o%3Aalice_becomes_happy"/>
    <test_engine>
        <tags enabled=""/>
        <status steps="0" coverage="0.000000" scov="0.000000e+00"/>
        <current_time time="1484623303.718879"/>
        <suggested_action type="input" name="i%3Acallee%3D%27Alice%27" time="1484623303.730120"/>
        <action type="input" name="i%3Acallee%3D%27Alice%27" time="1484623303.730224"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="1" coverage="0.166667" scov="1.666667e-01"/>
        <current_time time="1484623303.730449"/>
        <suggested_action type="input" name="i%3Acallee%3D%27Bob%27" time="1484623303.739919"/>
        <action type="input" name="i%3Acallee%3D%27Bob%27" time="1484623303.740106"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="2" coverage="0.333333" scov="3.333333e-01"/>
        <current_time time="1484623303.740377"/>
        <suggested_action type="input" name="i%3AphoneApp%3D%27Skype%27" time="1484623303.750421"/>
        <action type="input" name="i%3AphoneApp%3D%27Skype%27" time="1484623303.750515"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="3" coverage="0.500000" scov="5.000000e-01"/>
        <current_time time="1484623303.750704"/>
        <suggested_action type="input" name="i%3AphoneApp%3D%27WhatsApp%27" time="1484623303.762150"/>
        <action type="input" name="i%3AphoneApp%3D%27WhatsApp%27" time="1484623303.762437"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="4" coverage="0.666667" scov="6.666667e-01"/>
        <current_time time="1484623303.762761"/>
        <suggested_action type="input" name="i%3Acall" time="1484623303.773270"/>
        <action type="input" name="i%3Acall" time="1484623303.773448"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="5" coverage="0.833333" scov="8.333333e-01"/>
        <current_time time="1484623303.773651"/>
        <suggested_action type="input" name="i%3Acallee%3D%27Alice%27" time="1484623303.781869"/>
        <action type="input" name="i%3Acallee%3D%27Alice%27" time="1484623303.781998"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="6" coverage="0.833333" scov="8.333333e-01"/>
        <current_time time="1484623303.782203"/>
        <suggested_action type="input" name="i%3Acallee%3D%27Bob%27" time="1484623303.791488"/>
        <action type="input" name="i%3Acallee%3D%27Bob%27" time="1484623303.791618"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="7" coverage="0.833333" scov="8.333333e-01"/>
        <current_time time="1484623303.791890"/>
        <suggested_action type="input" name="i%3Acallee%3D%27Bob%27" time="1484623303.800178"/>
        <action type="input" name="i%3Acallee%3D%27Bob%27" time="1484623303.800272"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="8" coverage="0.833333" scov="8.333333e-01"/>
        <current_time time="1484623303.800459"/>
        <suggested_action type="input" name="i%3AphoneApp%3D%27WhatsApp%27" time="1484623303.808306"/>
        <action type="input" name="i%3AphoneApp%3D%27WhatsApp%27" time="1484623303.808401"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="9" coverage="0.833333" scov="8.333333e-01"/>
        <current_time time="1484623303.808587"/>
        <suggested_action type="input" name="i%3Acallee%3D%27Alice%27" time="1484623303.815662"/>
        <action type="input" name="i%3Acallee%3D%27Alice%27" time="1484623303.815801"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="10" coverage="0.833333" scov="8.333333e-01"/>
        <current_time time="1484623303.815991"/>
        <suggested_action type="input" name="i%3Acall" time="1484623303.824106"/>
        <action type="input" name="i%3Acall" time="1484623303.824197"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="11" coverage="0.833333" scov="8.333333e-01"/>
        <current_time time="1484623303.824354"/>
        <suggested_action type="input" name="i%3Acall" time="1484623303.831518"/>
        <action type="input" name="i%3Acall" time="1484623303.831756"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="12" coverage="0.833333" scov="8.333333e-01"/>
        <current_time time="1484623303.832037"/>
        <suggested_action type="input" name="i%3Acallee%3D%27Bob%27" time="1484623303.840432"/>
        <action type="input" name="i%3Acallee%3D%27Bob%27" time="1484623303.840520"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="13" coverage="0.833333" scov="8.333333e-01"/>
        <current_time time="1484623303.840704"/>
        <suggested_action type="input" name="i%3AphoneApp%3D%27WhatsApp%27" time="1484623303.847767"/>
        <action type="input" name="i%3AphoneApp%3D%27WhatsApp%27" time="1484623303.847885"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="14" coverage="0.833333" scov="8.333333e-01"/>
        <current_time time="1484623303.848141"/>
        <suggested_action type="input" name="i%3AphoneApp%3D%27WhatsApp%27" time="1484623303.857405"/>
        <action type="input" name="i%3AphoneApp%3D%27WhatsApp%27" time="1484623303.857495"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="15" coverage="0.833333" scov="8.333333e-01"/>
        <current_time time="1484623303.857716"/>
        <suggested_action type="input" name="i%3Acallee%3D%27Alice%27" time="1484623303.864792"/>
        <action type="input" name="i%3Acallee%3D%27Alice%27" time="1484623303.864888"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="16" coverage="0.833333" scov="8.333333e-01"/>
        <current_time time="1484623303.865084"/>
        <suggested_action type="input" name="i%3AphoneApp%3D%27WhatsApp%27" time="1484623303.872100"/>
        <action type="input" name="i%3AphoneApp%3D%27WhatsApp%27" time="1484623303.872188"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="17" coverage="0.833333" scov="8.333333e-01"/>
        <current_time time="1484623303.872372"/>
        <suggested_action type="input" name="i%3Acallee%3D%27Bob%27" time="1484623303.879674"/>
        <action type="input" name="i%3Acallee%3D%27Bob%27" time="1484623303.879957"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="18" coverage="0.833333" scov="8.333333e-01"/>
        <current_time time="1484623303.880246"/>
        <suggested_action type="input" name="i%3AphoneApp%3D%27Skype%27" time="1484623303.888400"/>
        <action type="input" name="i%3AphoneApp%3D%27Skype%27" time="1484623303.888511"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="19" coverage="0.833333" scov="8.333333e-01"/>
        <current_time time="1484623303.888781"/>
        <suggested_action type="input" name="i%3AphoneApp%3D%27WhatsApp%27" time="1484623303.897496"/>
        <action type="input" name="i%3AphoneApp%3D%27WhatsApp%27" time="1484623303.897618"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="20" coverage="0.833333" scov="8.333333e-01"/>
        <current_time time="1484623303.897840"/>
        <suggested_action type="input" name="i%3Acallee%3D%27Alice%27" time="1484623303.906322"/>
        <action type="input" name="i%3Acallee%3D%27Alice%27" time="1484623303.906419"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="21" coverage="0.833333" scov="8.333333e-01"/>
        <current_time time="1484623303.906608"/>
        <suggested_action type="input" name="i%3Acallee%3D%27Bob%27" time="1484623303.913862"/>
        <action type="input" name="i%3Acallee%3D%27Bob%27" time="1484623303.913968"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="22" coverage="0.833333" scov="8.333333e-01"/>
        <current_time time="1484623303.914160"/>
        <suggested_action type="input" name="i%3AphoneApp%3D%27WhatsApp%27" time="1484623303.921207"/>
        <action type="input" name="i%3AphoneApp%3D%27WhatsApp%27" time="1484623303.921335"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="23" coverage="0.833333" scov="8.333333e-01"/>
        <current_time time="1484623303.921577"/>
        <suggested_action type="input" name="i%3Acallee%3D%27Bob%27" time="1484623303.929212"/>
        <action type="input" name="i%3Acallee%3D%27Bob%27" time="1484623303.929333"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="24" coverage="0.833333" scov="8.333333e-01"/>
        <current_time time="1484623303.929564"/>
        <suggested_action type="input" name="i%3AphoneApp%3D%27Skype%27" time="1484623303.936604"/>
        <action type="input" name="i%3AphoneApp%3D%27Skype%27" time="1484623303.936701"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="25" coverage="0.833333" scov="8.333333e-01"/>
        <current_time time="1484623303.936890"/>
        <suggested_action type="input" name="i%3Acall" time="1484623303.943940"/>
        <action type="input" name="i%3Acall" time="1484623303.944052"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="26" coverage="0.833333" scov="8.333333e-01"/>
        <current_time time="1484623303.944224"/>
        <suggested_action type="input" name="i%3Acallee%3D%27Alice%27" time="1484623303.951686"/>
        <action type="input" name="i%3Acallee%3D%27Alice%27" time="1484623303.951813"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="27" coverage="0.833333" scov="8.333333e-01"/>
        <current_time time="1484623303.952020"/>
        <suggested_action type="input" name="i%3Acall" time="1484623303.959593"/>
        <action type="input" name="i%3Acall" time="1484623303.959712"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled=""/>
        <status steps="28" coverage="0.833333" scov="8.333333e-01"/>
        <current_time time="1484623303.959899"/>
        <action type="output" name="o%3Aalice_becomes_happy" time="1484623303.960116"/>
        <tags enabled=""/>
        <status steps="29" coverage="1.000000" scov="1.000000e+00"/>
        <current_time time="1484623303.960259"/>
        <stop verdict="pass" reason="coverage%201.0%20reached"/>
        <current_time time="1484623303.960279"/>
        <elapsed_time time="0.241599"/>
    </test_engine>
</conf_execute>
</fmbt_log>
```
the seperator options does not seems to be working:

```
root@NKG1000102834:~/work/# fmbt-log -f '$as$sc' -s ":"  test.log
i:callee='Alice'0.166667
i:callee='Bob'0.333333
i:phoneApp='Skype'0.500000
i:phoneApp='WhatsApp'0.666667
i:call0.833333
i:callee='Alice'0.833333
i:callee='Bob'0.833333
i:callee='Bob'0.833333
i:phoneApp='WhatsApp'0.833333
i:callee='Alice'0.833333
i:call0.833333
i:call0.833333
i:callee='Bob'0.833333
i:phoneApp='WhatsApp'0.833333
i:phoneApp='WhatsApp'0.833333
i:callee='Alice'0.833333
i:phoneApp='WhatsApp'0.833333
i:callee='Bob'0.833333
i:phoneApp='Skype'0.833333
i:phoneApp='WhatsApp'0.833333
i:callee='Alice'0.833333
i:callee='Bob'0.833333
i:phoneApp='WhatsApp'0.833333
i:callee='Bob'0.833333
i:phoneApp='Skype'0.833333
i:call0.833333
i:callee='Alice'0.833333
i:call0.833333
1.000000

```

**Comment by askervin** [comment]
You are probably looking for record separator (``-S``) instead of multi-value field separator (``-s``).

**Comment by dassio** [comment]
`fmbt-log -f '$as (coverage: $sc)' test.log `

this is not working 

```
fmbt-log -f '$as (coverage: $sc)' static_user_testsuit.log
Traceback (most recent call last):
  File "C:\Program Files\fMBT\fmbt-log", line 396, in <module>
    input_file_obj = codecs.open(logfilename, "r","utf8")
  File "C:\Python27\lib\codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 22] invalid mode ('rb') or filename: '(coverage:'
```

**Comment by askervin** [comment]
You're probably using ``cmd.exe`` as a shell in Windows. And it seems that when called like above, it gives fmbt-log parameters:
1: -f
2: '$as
3: (coverage:

and therefore fmbt-log tries to open file "(coverage:". Cmd.exe handles single quotes (') differently from Bash.

This should work on Windows:

``fmbt-log -f "$as (coverage: $sc)" static_user_testsuit.log``

Note that it doesn't work on Bash, because Bash would expand ``$as`` and ``$sc`` in the format string with values of corresponding environment variables.

**Comment by dassio** [comment]
thanks that works perfectly
